#!/usr/bin/env python
# encoding=utf-8

# Copyright 2009 Patrick Näf
# 
# This file is part of mkroesti
#
# mkroesti is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# mkroesti is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with mkroesti. If not, see <http://www.gnu.org/licenses/>.


# PSL
import sys
import os.path

# mkroesti
import mkroesti.main
import mkroesti.errorhandling


try:
    if __name__ == "__main__":
        scriptName = os.path.basename(sys.argv[0])
        mkroesti.main.main()
except (mkroesti.errorhandling.MKRoestiError,
        mkroesti.errorhandling.DuplicateAlgorithmError,
        mkroesti.errorhandling.DuplicateAliasError,
        mkroesti.errorhandling.DuplicateProviderError), (errorInstance):
    print scriptName + ": error: " + errorInstance.message
    exit(1)
except mkroesti.errorhandling.UnknownAlgorithmError, (errorInstance):
    print scriptName + ": " + errorInstance.message
    exit(1)
except mkroesti.errorhandling.UnavailableAlgorithmError, (errorInstance):
    print scriptName + ": " + errorInstance.message
    exit(1)
except mkroesti.errorhandling.UnknownAliasError, (errorInstance):
    print scriptName + ": unknown alias: " + errorInstance.message
    exit(1)
    