#!/usr/bin/env python
# encoding=utf-8

# PSL
import sys
import os.path

# mkroesti
import mkroesti.main
import mkroesti.errorhandling


try:
    if __name__ == "__main__":
        scriptName = os.path.basename(sys.argv[0])
        mkroesti.main.main()

except (mkroesti.errorhandling.MKRoestiError,
        mkroesti.errorhandling.DuplicateAlgorithmError,
        mkroesti.errorhandling.DuplicateAliasError,
        mkroesti.errorhandling.DuplicateProviderError), (errorInstance):
    print scriptName + ": error: " + errorInstance.message
    exit(1)
except mkroesti.errorhandling.UnknownAlgorithmError, (errorInstance):
    print scriptName + ": " + errorInstance.message
    exit(1)
except mkroesti.errorhandling.UnavailableAlgorithmError, (errorInstance):
    print scriptName + ": " + errorInstance.message
    exit(1)
except mkroesti.errorhandling.UnknownAliasError, (errorInstance):
    print scriptName + ": unknown alias: " + errorInstance.message
    exit(1)
    